Repository VaibhavSaini19/BootBlox, pull requests merged in 2020-10, with the labels that each got.

#16 Added GitHub Actions and templates for BootBlox
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  package.json
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#37 Feat: Blogs thumbnails
  assets/thumbs/blog_1_thub.svg
  assets/thumbs/blog_2_thumb.svg
  assets/thumbs/blog_3_thumb.svg
Labels: hacktoberfest-accepted

#33 Feat: Add pricing icons and logic to display them
  assets/thumbs/pricing_1_thumb.svg
  assets/thumbs/pricing_2_thumb.svg
Labels: hacktoberfest-accepted, under-review

#38 Added svg thumbnails for hero blocks
  assets/thumbs/hero_1_thumb.svg
  assets/thumbs/hero_2_thumb.svg
Labels: under-review

#49 Feat: Add Feature section thumbnail icon
  assets/thumbs/feature_1_thumb.svg
Labels: hacktoberfest-accepted
